# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AIF',
                'doc_host': 'https://erling6232.github.io',
                'git_url': 'https://github.com/erling6232/AIF',
                'lib_path': 'AIF'},
  'syms': {'AIF.core': {'AIF.core.foo': ('core.html#foo', 'AIF/core.py')}}}
