# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AIF',
                'doc_host': 'https://erling6232.github.io',
                'git_url': 'https://github.com/erling6232/AIF',
                'lib_path': 'AIF'},
  'syms': { 'AIF.AIF': {'AIF.AIF.foo': ('core.html#foo', 'AIF/AIF.py')},
            'AIF.core': {'AIF.core.foo': ('parker.html#foo', 'AIF/core.py')},
            'AIF.parker': {'AIF.parker.foo': ('parker.html#foo', 'AIF/parker.py')}}}
