project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Get Started"
        href: 00_parker.ipynb
    right:
      - icon: github
        href: "https://github.com/erling6232/AIF"
  sidebar:
    style: floating
    contents:
      - auto: "*.ipynb"


# metadata-files: [nbdev.yml, sidebar.yml]
metadata-files: [nbdev.yml]
